#!/bin/bash

# Remove other versions of Gazebo first.
# Having install ros-indigo-desktop-full:
# sudo apt-get remove gazebo2

sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

sudo apt-get update
sudo apt-get install -y ros-indigo-gazebo6-ros-pkgs

# sudo apt-get install libgazebo6-dev
