#!/bin/bash

# First, because [ENTER] key...
# PS3 Controller drivers:

sudo apt-add-repository ppa:falk-t-j/qtsixa
sudo apt-get update
sudo apt-get install -y sixad

# ROS Indigo Igloo:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xB01FA116

sudo apt-get update
sudo apt-get install -y ros-indigo-desktop-full

sudo rosdep init
rosdep update

echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc

# ROS check_urdf:

sudo apt-get install -y liburdfdom-tools

# ROS Webcam driver:

sudo apt-get install -y ros-indigo-usb-cam

# ROS Joystick driver:

sudo apt-get install -y ros-indigo-joy

# ROS Kinect driver:

sudo apt-get install -y freenect ros-indigo-freenect-launch

# ROS Navigation stuff 'n thangs:

sudo apt-get install -y ros-indigo-depthimage-to-laserscan
sudo apt-get install -y ros-indigo-slam-gmapping
