#!/bin/bash

sudo apt-get install -y freenect ros-indigo-freenect-launch

sudo apt-get install -y ros-indigo-depthimage-to-laserscan
#sudo apt-get install -y ros-indigo-pointcloud-to-laserscan

sudo apt-get install -y ros-indigo-slam-gmapping
