#!/bin/bash

# PS3 Controller drivers:

sudo apt-add-repository -y ppa:falk-t-j/qtsixa
sudo apt-get update
sudo apt-get install -y sixad

# ROS check_urdf:

sudo apt-get install -y liburdfdom-tools

# ROS Webcam driver:

sudo apt-get install -y ros-indigo-usb-cam

# ROS Joystick driver:

sudo apt-get install -y ros-indigo-joy

# ROS Kinect driver:

sudo apt-get install -y freenect ros-indigo-freenect-launch

# ROS Navigation stuff 'n thangs:

sudo apt-get install -y ros-indigo-depthimage-to-laserscan
sudo apt-get install -y ros-indigo-slam-gmapping
